package io.exko.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate

class StyledProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    companion object {
        private const val ANNOTATION_NAME = "io.exko.styled.Css"
        private const val OUTPUT_PACKAGE = "io.exko.styled"
        private const val OUTPUT_FILE = "RegisterStyled"
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_NAME)
        val unprocessed = symbols.filter { !it.validate() }.toList()

        val styledObjects = symbols
            .filter { it.validate() }
            .filterIsInstance<KSClassDeclaration>()
            .filter { declaration ->
                if (declaration.classKind != ClassKind.OBJECT) {
                    logger.error(
                        "@Css can only be applied to object declarations",
                        declaration,
                    )
                    false
                } else {
                    true
                }
            }
            .toList()

        if (styledObjects.isEmpty()) return unprocessed

        val dependencies = Dependencies(
            aggregating = true,
            sources = styledObjects.mapNotNull { it.containingFile }.toTypedArray(),
        )

        codeGenerator.createNewFile(dependencies, OUTPUT_PACKAGE, OUTPUT_FILE).bufferedWriter().use { writer ->
            writer.write("// Generated by StyledProcessor — do not edit\n")
            writer.write("package $OUTPUT_PACKAGE\n\n")

            writer.write("import io.exko.styled.StyledBundler\n")
            styledObjects.forEach { obj ->
                val qualifiedName = obj.qualifiedName?.asString() ?: return@forEach
                writer.write("import $qualifiedName\n")
            }
            writer.write("\nprivate var action: () -> Unit = {}\n")

            writer.write("\nfun registerStyled(callback: (() -> Unit)? = null) {\n")
            writer.write("    callback?.let { action = it }\n")
            writer.write("    StyledBundler.clear()\n")
            writer.write("    StyledBundler.registerAll(\n        setOf(\n")
            styledObjects.forEach { obj ->
                val simpleName = obj.simpleName.asString()
                writer.write("            $simpleName,\n")
            }
            writer.write("        ),\n    )\n")
            writer.write("    action()\n")
            writer.write("}\n")
        }

        return unprocessed
    }
}
