package io.exko.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate
import java.security.MessageDigest

class StyledProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    companion object {
        private const val ANNOTATION_NAME = "io.exko.styled.Css"
        private const val OUTPUT_PACKAGE = "io.exko.styled.generated"
        private const val SERVICE_INTERFACE = "io.exko.styled.StyledRegistrar"
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_NAME)
        val unprocessed = symbols.filter { !it.validate() }.toList()

        val styledObjects = symbols
            .filter { it.validate() }
            .filterIsInstance<KSClassDeclaration>()
            .filter { declaration ->
                if (declaration.classKind != ClassKind.OBJECT) {
                    logger.error(
                        "@Css can only be applied to object declarations",
                        declaration,
                    )
                    false
                } else {
                    true
                }
            }
            .toList()

        if (styledObjects.isEmpty()) return unprocessed

        val dependencies = Dependencies(
            aggregating = true,
            sources = styledObjects.mapNotNull { it.containingFile }.toTypedArray(),
        )

        val hash = styledObjects
            .mapNotNull { it.qualifiedName?.asString() }
            .sorted()
            .joinToString(",")
            .let { sha256(it).take(8) }
        val className = "StyledRegistrar_$hash"

        codeGenerator.createNewFile(dependencies, OUTPUT_PACKAGE, className).bufferedWriter().use { writer ->
            writer.write("// Generated by StyledProcessor — do not edit\n")
            writer.write("package $OUTPUT_PACKAGE\n\n")

            writer.write("import io.exko.styled.StyledBundler\n")
            writer.write("import io.exko.styled.StyledRegistrar\n")
            styledObjects.forEach { obj ->
                val qualifiedName = obj.qualifiedName?.asString() ?: return@forEach
                writer.write("import $qualifiedName\n")
            }

            writer.write("\nclass $className : StyledRegistrar {\n\n")
            writer.write("    override fun register(bundler: StyledBundler) {\n")
            writer.write("        bundler.registerAll(\n            setOf(\n")
            styledObjects.forEach { obj ->
                val simpleName = obj.simpleName.asString()
                writer.write("                $simpleName,\n")
            }
            writer.write("            ),\n        )\n")
            writer.write("    }\n")
            writer.write("}\n")
        }

        codeGenerator.createNewFile(
            dependencies,
            "",
            "META-INF/services/io.exko.styled.StyledRegistrar",
            "",
        ).use { output ->
            output.write("$OUTPUT_PACKAGE.$className\n".toByteArray())
        }

        return unprocessed
    }

    private fun sha256(input: String): String {
        val digest = MessageDigest.getInstance("SHA-256")
        return digest.digest(input.toByteArray()).joinToString("") { "%02x".format(it) }
    }
}
